### ISSUE TITLE
v0.2.0.2におけるmyprofile.jsonの「,」の過剰表記

### ISSUE THREAD

**Issue by pipolll** [isletennos/MMVC_Client#9]
myprofile.jsonの
```
"voice_list": [107, 100, 1, 10, 20, 30],
```
について、最後の,(カンマ)は除去する必要があると思います。
各{ }内の最後の要素（この場合はothers{}内）の行末に , があると、
MMVC_client_GPU.pyにて読み込みに失敗し、エラー終了します。
voice_list最後の , を除去した状態でMMVC_client_GPU.pyの読み込み、実行ができた事は確認しました。

**Comment by isletennos** [comment]
ありがとうございます！
こちら対応いたしました！
